exclude:
  - package.json
  - node_modules
  - gulpfile.js

baseurl: '/'
url: 'https://naughty-benz-71351a.netlify.app/'

related_posts_amount: 4

defaults:
  - scope:
      path: ''
      type: 'category'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:slugified_categories/:title'
      excerpt_separator: <!--more-->
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-paginate-v2

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # How many posts to show per page. Temporary 3 - for debugging
  per_page: 8
  debug: false
  sort_field: 'date'
  sort_reverse: true
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  permalink: '/page/:num/'

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'
    slugify:
      mode: 'default' # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: true # Whether to replace all uppercase letters with their lowercase counterparts

  # Tag pages, omit to disable
  tags:
    title: 'Posts tagged with #:tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    slugify:
      mode: 'default' # :tag is slugified.
      case: false
